language: java
jdk: oraclejdk8

install: true
script: mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
cache:
  directories:
  - $HOME/.m2
  
  
notifications:
  email:
    recipients:
          - vardan27a@gmail.com
          - nadrav27@gmail.com
        on_success: always # default: change (change, never, always)
        on_failure: always # default: always